---
abstract: 'searchable, orderable, flexible sets of (almost) anything.'
author:
  - 'Sir Robert Burbridge <sirrobert@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Set-Toolkit
version: 0.13
