---
abstract: 'searchable, orderable, flexible sets of (almost) anything.'
author:
  - 'Sir Robert Burbridge <sirrobert@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Set-Toolkit
provides:
  Set::Toolkit:
    file: lib/Set/Toolkit.pm
    version: 0.10
  Set::Toolkit::TieArray:
    file: lib/Set/Toolkit.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
